production:
  adapter: postgresql
  host: db.schemaverse.com
  database: schemaverse

# For now we are using the live server for testing.  Bad implementation
# but for a first release it is a big task to mock the functionality of the SV
test:
  username:
  password: 
  adapter: postgresql
  host: db.schemaverse.com
  database: schemaverse
